### ISSUE TITLE
Implement changes in worker

### ISSUE THREAD

**Issue by AGrzes** [AGrzes/command-center#42]
- [x] AGrzes/command-center-worker#2
- [x] AGrzes/command-center-worker#5
- [x] AGrzes/command-center-worker#6
- [x] AGrzes/command-center-worker#7
- [x] AGrzes/command-center-worker#8
- [x] AGrzes/command-center-worker#9
